Repository SWT-Forschungsprojekt/realtime-metrics, pull requests merged in 2025-05, with the labels that each got.

#8 Grammar fixes and gtfsrdb command corrected -v mean verbose output (which is used to see e.g., the number of vehiclePositions) while -p stands for the vehiclePositions URL
  README.md
Labels: bug, documentation

#10 Implement prediction reliability metric
  src/realtime_metrics/gtfsdb_models.py
  src/realtime_metrics/main.py
Labels: enhancement

#9 Implement prediction inconsistency metric
  src/realtime_metrics/main.py
Labels: enhancement

#14 Fix accuracy calculation
  src/realtime_metrics/main.py
Labels: bug
